deploy:
docker:
  - image: circleci/node:chakracore-8.11.1
steps
  - run:
      name: AWS EC2 deploy
      command: |
        #upload all the code to machine
        scp -r -o StrictHostKeyChecking=no ./ ubuntu@3.112.44.244:/home/ubuntu/testci
        #Run script inside of machine
        ssh -o StrictHostKeyChecking=no ubuntu@3.112.44.244 "./deploy.sh"
